### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by xblox** [xblox/control-freak#1]
Talking with Marlin Firmware (3D-Printer)
![3dprinter](https://cloud.githubusercontent.com/assets/1205100/25517115/3845ff0c-2bee-11e7-826a-3f3562eb46f6.png)

Interface building for AV-Hardware in a theatre
![11fb28b6-8ccc-11e6-8d14-4ff528f35c9d](https://cloud.githubusercontent.com/assets/1205100/25517145/4cf9de5a-2bee-11e7-8860-0a9c884b3eb4.png)

![vlc](https://cloud.githubusercontent.com/assets/1205100/25517168/67353ada-2bee-11e7-9c1c-3e9c086b60af.png)

Talking with VLC
![632e2aa2-c256-11e6-8435-e00cfde82537](https://cloud.githubusercontent.com/assets/1205100/25517164/64ad1530-2bee-11e7-8b45-487695f43d8f.png)

**Comment by tx4x** [comment]
widget states, addressable via commands & variables 
![image](https://user-images.githubusercontent.com/1205100/33748633-e2052d3e-dbc9-11e7-8fc0-71b8a60d3b01.png)

**Comment by tx4x** [comment]
![image](https://user-images.githubusercontent.com/1205100/33801441-965e017e-dd5b-11e7-83b8-1897a9be794c.png)

**Comment by tx4x** [comment]
current rewrite progress: 
![xcf2](https://user-images.githubusercontent.com/1205100/41845704-a87f971e-7874-11e8-854d-fd7a8ba051ff.png)
